name: autoplex_training
log_level: debug
workers:
  sumo_worker:
    type: remote
    scheduler_type: slurm
    work_dir: /scratch/work/zarrout1/autoplex/run
    host: tr
    max_jobs: 10
    pre_run: |
      source ~/.bashrc
      module load mamba
      mamba activate autoplex_pyenv
  roihu_gpu_worker:
    type: remote
    scheduler_type: slurm
    work_dir: /scratch/project_2017844/autoplex/run/aims
    host: roihug
    max_jobs: 10
    pre_run: |
      source /etc/profile 
      source ~/.bashrc
      module load python-data/3.12
      source /projappl/project_2017844/autoplex_pyenv/bin/activate
  roihu_vasp_worker:
    type: remote
    scheduler_type: slurm
    work_dir: /scratch/project_2017844/autoplex/run/vasp
    host: roihuc
    max_jobs: 100
    pre_run: |
      source /etc/profile 
      source ~/.bashrc
      module load python-data/3.12
      source /projappl/project_2017844/autoplex_pyenv/bin/activate
  roihu_worker:
    type: remote
    scheduler_type: slurm
    work_dir: /scratch/project_2017844/autoplex/run/general
    host: roihuc
    max_jobs: 100
    pre_run: |
      source /etc/profile 
      source ~/.bashrc
      module load python-data/3.12
      source /projappl/project_2017844/autoplex_pyenv/bin/activate
  roihu_batch_worker:
    type: remote
    scheduler_type: slurm
    work_dir: /scratch/project_2017844/autoplex/run/aims
    host: roihuc
    pre_run: |
      source /etc/profile 
      source ~/.bashrc
      module load python-data/3.12
      source /projappl/project_2017844/autoplex_pyenv/bin/activate
    max_jobs: 10
    batch:
      jobs_handle_dir: /scratch/project_2017844/autoplex/run/aims/jobs_handle
      work_dir: /scratch/project_2017844/autoplex/run/aims/batch
  roihu_batch_parallel_worker:
    type: remote
    scheduler_type: slurm
    work_dir: /scratch/project_2017844/autoplex/run/aims
    host: roihuc
    pre_run: |
      source /etc/profile 
      source ~/.bashrc
      module load python-data/3.12
      source /projappl/project_2017844/autoplex_pyenv/bin/activate
    max_jobs: 10
    batch:
      jobs_handle_dir: /scratch/project_2017844/autoplex/run/aims/jobs_handle
      work_dir: /scratch/project_2017844/autoplex/run/aims/batch
      parallel_jobs: 4
  roihu_shell_worker:
    type: remote
    scheduler_type: shell
    work_dir: /scratch/project_2017844/autoplex/run/aims
    host: roihuc
    pre_run: |
      source /etc/profile 
      source ~/.bashrc
      module load python-data/3.12
      source /projappl/project_2017844/autoplex_pyenv/bin/activate
    max_jobs: 3
queue:
  store:
    type: MongoStore
    host: 86.50.169.72
    port: 33306
    username: tigany
    password: CHANGEME
    database: autoplex
    collection_name: queue
  flows_collection: flows_autoplex
  auxiliary_collection: jf_auxiliary_autoplex 
  batches_collection: batches_autoplex 
exec_config: 
  roihu_aims_gpu_config:
    modules: 
    - nvhpc 
    export: 
      AIMS_ROOT: "/projappl/project_2017844/install/gpu/FHIaims"
      ELPA_ROOT: "/projappl/project_2017844/install/gpu/elpa-2026.02.002"
      AIMS_BUILD: "build_nvhpc_seq_gpu"
      AIMS_BUILD_DIR: "${AIMS_ROOT}/${AIMS_BUILD}"
      ELPA_BUILD_DIR: "${ELPA_ROOT}/${AIMS_BUILD}"
      AIMS_SPECIES_DIR: "${AIMS_ROOT}/species_defaults/defaults_2020"
      LD_LIBRARY_PATH: "${ELPA_BUILD_DIR}/lib:${LD_LIBRARY_PATH}"
      INCLUDE: "${ELPA_BUILD_DIR}/modules:${INCLUDE}"
      PATH: "${AIMS_BUILD_DIR}:${PATH}"
      PYTHONPATH: "/scratch/project_2017844/autoplex/dks_flows:${PYTHONPATH}"
      autoplex_CONFIG_FILE: "/scratch/project_2017844/autoplex/config/autoplex.yaml"
    pre_run: |
      source /etc/profile 
      source ~/.bashrc
      ulimit -s unlimited
  roihu_aims_config:
    modules: 
    - gcc/15.2.0 
    - openmpi/5.0.10 
    - openblas/0.3.30
    - netlib-scalapack/2.2.2
    export: 
      AIMS_ROOT: "/projappl/project_2017844/install/FHIaims"
      ELPA_ROOT: "/projappl/project_2017844/install/elpa-2026.02.001"
      AIMS_BUILD: "build_gnu_17_no_openmp_openmpi_avx512_cpu"
      AIMS_BUILD_DIR: "${AIMS_ROOT}/${AIMS_BUILD}"
      ELPA_BUILD_DIR: "${ELPA_ROOT}/${AIMS_BUILD}"
      AIMS_SPECIES_DIR: "${AIMS_ROOT}/species_defaults/defaults_2020"
      LD_LIBRARY_PATH: "${ELPA_BUILD_DIR}/lib:${LD_LIBRARY_PATH}"
      INCLUDE: "${ELPA_BUILD_DIR}/modules:${INCLUDE}"
      PATH: "${AIMS_BUILD_DIR}:${PATH}"
      PYTHONPATH: "/scratch/project_2017844/autoplex/dks_flows:${PYTHONPATH}"
      OMP_NUM_THREADS: 1
      autoplex_CONFIG_FILE: "/scratch/project_2017844/autoplex/config/autoplex.yaml"
    pre_run: |
      source /etc/profile 
      source ~/.bashrc
      ulimit -s unlimited
  roihu_aims_parallel_config:
    modules: 
    - gcc/15.2.0 
    - openmpi/5.0.10 
    - openblas/0.3.30
    - netlib-scalapack/2.2.2
    export: 
      AIMS_ROOT: "/projappl/project_2017844/install/FHIaims"
      ELPA_ROOT: "/projappl/project_2017844/install/elpa-2026.02.001"
      AIMS_BUILD: "build_gnu_17_no_openmp_openmpi_avx512_cpu"
      AIMS_BUILD_DIR: "${AIMS_ROOT}/${AIMS_BUILD}"
      ELPA_BUILD_DIR: "${ELPA_ROOT}/${AIMS_BUILD}"
      AIMS_SPECIES_DIR: "${AIMS_ROOT}/species_defaults/defaults_2020"
      LD_LIBRARY_PATH: "${ELPA_BUILD_DIR}/lib:${LD_LIBRARY_PATH}"
      INCLUDE: "${ELPA_BUILD_DIR}/modules:${INCLUDE}"
      PATH: "${AIMS_BUILD_DIR}:${PATH}"
      PYTHONPATH: "/scratch/project_2017844/autoplex/dks_flows:${PYTHONPATH}"
      OMP_NUM_THREADS: 1
      autoplex_CONFIG_FILE: "/scratch/project_2017844/autoplex/config/autoplex.yaml"
      autoplex_AIMS_CMD: "srun --nodes 1 -n 384 --exclusive aims > aims.out"
    pre_run: |
      source /etc/profile 
      source ~/.bashrc
      ulimit -s unlimited
jobstore:
  docs_store:
    type: MongoStore
    database: autoplex
    host: 86.50.169.72
    port: 33306
    username: tigany
    password: CHANGEME
    collection_name: outputs
  additional_stores:
    data:
      type: GridFSStore
      database: autoplex
      host: 86.50.169.72
      port: 33306
      username: tigany
      password: CHANGEME
      collection_name: outputs_blobs
