#!/usr/bin/env python3
"""Render the jobflow-remote and atomate2 configuration from machines.conf.

Reads the JSON that ``setup/lib/common.sh:dump_machines_json`` writes on stdin
(or from ``--machines-json``) and writes into ``config/generated/``:

    jobflow_remote.yaml   the jobflow-remote project
    atomate2.yaml         the atomate2 command settings
    env.<machine>.sh      per-machine environment, sourced by the workers

Deliberately stdlib-only: this runs on the bare system interpreter of whatever
machine is bootstrapping, before any virtual environment exists.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

#: Roles that get a worker of their own, in the order they appear in a project.
ROLES = ("vasp", "aims", "turbogap", "gapfit")

#: Resources a role asks for when the workflow does not override them.
#:
#: A fallback, not a recommendation: a workflow that cares should set its own,
#: and one whose structures vary in size should set ``resource_tiers`` so each
#: calculation is sized to what it is calculating.
#:
#: FHI-aims takes a whole node, because that is the unit it is worth running on
#: for anything but the smallest cluster -- Roihu nodes are 384 cores and 762 GB
#: -- and a system around 200 atoms wants two, which means the `medium`
#: partition since `small` is single-node.
DEFAULT_RESOURCES = {
    "vasp": {"nodes": 1, "ntasks_per_node": 128, "time": "02:00:00"},
    "aims": {"nodes": 1, "ntasks_per_node": 384, "time": "01:00:00"},
    "turbogap": {"nodes": 1, "ntasks_per_node": 64, "time": "04:00:00"},
    "gapfit": {"nodes": 1, "cpus_per_task": 48, "time": "1-00:00:00"},
}


def worker_name(machine: dict, role: str | None = None) -> str:
    """Worker label for a machine, optionally specialised to one role."""
    base = machine["name"].replace("-", "_")
    return f"{base}_{role}" if role else f"{base}_worker"


def roles_of(machine: dict) -> list[str]:
    """The declared roles of a machine, in canonical order."""
    declared = {r.strip() for r in machine["roles"].split(",") if r.strip()}
    return [role for role in ROLES if role in declared]


def is_runner(machine: dict) -> bool:
    """Whether this machine hosts the jobflow-remote runner."""
    return "runner" in {r.strip() for r in machine["roles"].split(",")}


def venv_path(machine: dict) -> str:
    """Where setup_env_uv.sh puts this machine's virtual environment."""
    return f"{machine['work_dir'].rstrip('/')}/autoplex_venv"


def env_file_path(machine: dict) -> str:
    """Where setup_all_machines.sh puts this machine's environment file."""
    return f"{machine['work_dir'].rstrip('/')}/env.sh"


#: The module bootstrap, shared with the setup scripts rather than copied.
_MODULES_SH = Path(__file__).resolve().parent / "lib" / "modules.sh"


def module_init_snippet() -> str:
    """``setup/lib/modules.sh``, inlined so env.sh stands on its own.

    A worker sources env.sh and nothing else -- it has no way to reach
    setup/lib/ -- so the function is embedded rather than sourced. Reading it
    from the one file keeps the two copies from drifting.
    """
    return _MODULES_SH.read_text().rstrip()


def module_list(machine: dict) -> list[str]:
    """Modules this machine needs, the Python one first.

    ``python_module`` leads because the rest are compilers and libraries that
    a Python module can otherwise displace on PATH.
    """
    modules = []
    if machine["python_module"]:
        modules.append(machine["python_module"])
    modules += [m.strip() for m in machine["modules"].split(",") if m.strip()]
    return modules


def machine_env_sh(machine: dict) -> str:
    """The env.sh that lands in a machine's work_dir and every worker sources.

    Keeping this in one file per machine means a worker's ``pre_run`` stays a
    single ``source`` line, and a machine's environment can be repaired by hand
    without regenerating the whole project.
    """
    work_dir = machine["work_dir"].rstrip("/")
    lines = [
        "#!/usr/bin/env bash",
        f"# Environment for '{machine['name']}'. Generated by setup/render_config.py;",
        "# rewritten by every setup run, so edit config/machines.conf instead.",
        "",
        f"export AUTOPLEX_WORK_DIR={work_dir}",
        f"export AUTOPLEX_VENV={venv_path(machine)}",
        'export AUTOPLEX_REPO="$AUTOPLEX_WORK_DIR/autoplex_soap_turbo"',
        "",
    ]

    if machine["python_module"] or machine["modules"]:
        lines += module_init_snippet().splitlines()
        lines.append("init_module_system || echo \"env.sh: no 'module' command on $(hostname)\" >&2")
        for module in module_list(machine):
            # Not `|| true`: a worker that runs against the system Python
            # instead of the one it asked for fails much later and much less
            # legibly than a load that says so here.
            lines.append(f'module load {module} || echo "env.sh: module load {module} failed" >&2')
        lines.append("")

    machine_roles = roles_of(machine)

    # The external gap_fit environment goes in *before* the virtual environment,
    # not after. These files are somebody else's and they do more than put a
    # binary on PATH -- Triton's activates a conda environment -- so sourcing
    # one after the venv leaves `python` pointing somewhere with no autoplex in
    # it. Activating the venv last means its bin/ sits ahead of whatever the
    # gap_fit environment brought, while gap_fit itself, living elsewhere, is
    # still found.
    gapfit_dir_var = None
    if "gapfit" in machine_roles:
        gap_env = machine["gap_fit_env"]
        if gap_env:
            lines += [
                "# Pre-existing QUIP build with soap_turbo and dipole support.",
                f'if [ -f "{gap_env}" ]; then source "{gap_env}"; fi',
            ]
        else:
            lines += [
                "# QUIP built by setup/build_quip.sh.",
                'export PATH="$AUTOPLEX_WORK_DIR/quip/bin:$PATH"',
            ]
        lines += [
            "# Remember where that gap_fit lives. The virtual environment is",
            "# activated next and it ships a gap_fit of its own -- quippy-ase",
            "# bundles one, without soap_turbo and without dipoles -- which would",
            "# otherwise win on PATH and quietly fit the wrong thing.",
            'AUTOPLEX_GAPFIT_DIR="$(command -v gap_fit >/dev/null 2>&1 '
            '&& dirname "$(command -v gap_fit)")"',
            "",
        ]
        gapfit_dir_var = True

    lines += [
        'if [ -f "$AUTOPLEX_VENV/bin/activate" ]; then',
        '    source "$AUTOPLEX_VENV/bin/activate"',
        "fi",
        "",
    ]

    if gapfit_dir_var:
        lines += [
            "# Put the real QUIP back in front of the one the venv brought.",
            'if [ -n "$AUTOPLEX_GAPFIT_DIR" ]; then',
            '    export PATH="$AUTOPLEX_GAPFIT_DIR:$PATH"',
            "fi",
            "",
        ]

    if "turbogap" in machine_roles:
        turbogap = machine["turbogap_bin"]
        if turbogap:
            lines += [f'export TURBOGAP_BIN="{turbogap}"']
        else:
            lines += [
                'export TURBOGAP_ROOT="$AUTOPLEX_WORK_DIR/turbogap"',
                'export TURBOGAP_BIN="$TURBOGAP_ROOT/bin/turbogap"',
                'export PATH="$TURBOGAP_ROOT/bin:$PATH"',
            ]
        lines.append("")

    lines += [
        'export ATOMATE2_CONFIG_FILE="$AUTOPLEX_WORK_DIR/config/atomate2.yaml"',
        "ulimit -s unlimited 2>/dev/null || true",
        "",
    ]
    return "\n".join(lines)


def worker_block(machine: dict, role: str | None) -> list[str]:
    """One ``workers:`` entry, as indented YAML lines."""
    indent = " " * 4
    lines = [f"  {worker_name(machine, role)}:"]
    lines.append(f"{indent}type: {'local' if is_runner(machine) else 'remote'}")
    lines.append(f"{indent}scheduler_type: {machine['scheduler']}")

    work_dir = machine["work_dir"].rstrip("/")
    lines.append(f"{indent}work_dir: {work_dir}/run/{role or 'general'}")

    if not is_runner(machine):
        lines.append(f"{indent}host: {machine['host']}")

    lines.append(f"{indent}max_jobs: {machine['max_jobs']}")

    # jobflow-remote checks a worker by running a command and requiring exactly
    # "test" back on both streams. A cluster login shell rarely obliges: Roihu's
    # .bashrc complains that `module` is undefined, and `module load` prints a
    # banner. Neither is an error, but both land on the worker's output and make
    # every command look like it failed. This tells jobflow-remote to pick its
    # own output out of the surrounding noise.
    lines.append(f"{indent}sanitize_command: true")

    if machine["scheduler"] == "slurm" and machine["account"]:
        # jobflow-remote merges these into every submission script for the
        # worker, so a workflow only has to name the worker to land on the
        # right account and partition.
        lines.append(f"{indent}resources:")
        lines.append(f"{indent}  account: {machine['account']}")
        if machine["partition"]:
            lines.append(f"{indent}  partition: {machine['partition']}")
        for key, value in DEFAULT_RESOURCES.get(role or "", {}).items():
            lines.append(f"{indent}  {key}: {value}")

    lines.append(f"{indent}pre_run: |")
    lines.append(f"{indent}  source /etc/profile 2>/dev/null || true")
    lines.append(f"{indent}  source ~/.bashrc 2>/dev/null || true")
    lines.append(f"{indent}  source {env_file_path(machine)}")
    return lines


def store_block(
    config: dict, collection: str, indent: int, kind: str = "MongoStore"
) -> list[str]:
    """A maggma store definition pointing at the configured MongoDB."""
    mongo = config["mongodb"]
    pad = " " * indent
    lines = [
        f"{pad}type: {kind}",
        f"{pad}host: {mongo['host']}",
        f"{pad}port: {mongo['port']}",
        f"{pad}database: {mongo['database']}",
        f"{pad}username: {mongo['username']}",
        f"{pad}password: {mongo['password']}",
    ]
    if mongo.get("auth_source"):
        lines.append(f"{pad}auth_source: {mongo['auth_source']}")
    lines.append(f"{pad}collection_name: {collection}")
    return lines


def render_project(config: dict, exec_configs: str) -> str:
    """The complete jobflow-remote project file."""
    project = config["project_name"]
    lines = [
        f"# jobflow-remote project '{project}'.",
        "# Generated by setup/render_config.py from config/machines.conf and",
        "# config/exec_configs.yaml. Do not edit: every setup run rewrites it.",
        f"name: {project}",
        "log_level: info",
    ]

    # Where jobflow-remote stages files downloaded from the workers.
    #
    # It defaults to a `tmp/` folder under ~/.jfremote, which on an Aalto
    # workstation is the home volume -- and that volume has a *file* quota of
    # 1,000,000 inodes, already spent, while `df` still reports hundreds of
    # gigabytes free. Every completed calculation then fails to come back with
    #
    #     OSError: [Errno 122] Disk quota exceeded:
    #     '.jfremote/autoplex/tmp/download/...'
    #
    # after the DFT has already run: the job reaches TERMINATED on the worker,
    # the runner retries three times, and the whole flow stalls in REMOTE_ERROR
    # with its results sitting intact on the cluster. Same reason `work_dir` is
    # on local disk; this is the one path that was left behind.
    runner = next(
        (m for m in config["machines"] if is_runner(m)), None
    )
    if runner is not None:
        lines.append(f"tmp_dir: {runner['work_dir']}/jfremote_tmp")

    lines.append("workers:")

    for machine in config["machines"]:
        # A general-purpose worker on every machine, so light jobs (data
        # handling, structure selection) have somewhere to run without needing
        # a role of their own.
        lines += worker_block(machine, None)
        for role in roles_of(machine):
            lines += worker_block(machine, role)

    lines.append("queue:")
    lines.append("  store:")
    lines += store_block(config, "queue", indent=4)
    # Only the collections jobflow-remote's QueueConfig declares. Like
    # atomate2's settings it forbids extras, so an unknown key does not get
    # ignored -- the project file fails to parse and `jf` reports no project at
    # all, which looks like a missing file rather than a bad one.
    lines.append(f"  flows_collection: flows_{project}")
    lines.append(f"  auxiliary_collection: jf_auxiliary_{project}")

    if exec_configs.strip():
        lines.append("exec_config:")
        lines += [
            "  " + line if line.strip() else line
            for line in exec_configs.splitlines()
        ]

    lines.append("jobstore:")
    lines.append("  docs_store:")
    lines += store_block(config, "outputs", indent=4)
    lines.append("  additional_stores:")
    lines.append("    data:")
    lines += store_block(config, "outputs_blobs", indent=6, kind="GridFSStore")

    return "\n".join(lines) + "\n"


def render_atomate2(config: dict) -> str:
    """The atomate2 settings file shared by every machine.

    Only keys ``Atomate2Settings`` actually declares. Its model is
    ``extra="forbid"``, so one key it does not know does not get ignored -- it
    makes ``import atomate2`` raise a pydantic ValidationError on every machine
    that has ATOMATE2_CONFIG_FILE pointing here, which is every worker. The
    symptom is every VASP and FHI-aims job failing at import, a long way from
    the file that caused it.
    """
    vasp_cmds = sorted({m["vasp_cmd"] for m in config["machines"] if m["vasp_cmd"]})
    vasp_cmd = vasp_cmds[0] if vasp_cmds else "srun vasp_std"
    return (
        "# Generated by setup/render_config.py. Do not edit.\n"
        f'VASP_CMD: "{vasp_cmd}"\n'
        'VASP_GAMMA_CMD: "srun vasp_gam"\n'
        "# The FHI-aims exec_config prepends its build directory to PATH.\n"
        'AIMS_CMD: "srun aims > aims.out"\n'
    )


def strip_top_level_comments(text: str) -> str:
    """Drop unindented comment lines, so the spliced exec_config stays readable.

    Comments inside a block are indented and are kept, because they may be part
    of a ``pre_run`` literal block where dropping a line changes the script.
    """
    return "\n".join(
        line
        for line in text.splitlines()
        if not (line.startswith("#") or line.strip() == "")
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--machines-json",
        type=Path,
        help="JSON from dump_machines_json (default: read stdin)",
    )
    parser.add_argument(
        "--exec-configs",
        type=Path,
        help="config/exec_configs.yaml, spliced in verbatim",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        required=True,
        help="directory to write the rendered files into",
    )
    args = parser.parse_args()

    raw = args.machines_json.read_text() if args.machines_json else sys.stdin.read()
    config = json.loads(raw)

    exec_configs = ""
    if args.exec_configs and args.exec_configs.is_file():
        exec_configs = strip_top_level_comments(args.exec_configs.read_text())

    out_dir = args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    project_file = out_dir / "jobflow_remote.yaml"
    project_file.write_text(render_project(config, exec_configs))
    # It holds the MongoDB password: readable by its owner only.
    project_file.chmod(0o600)
    print(f"wrote {project_file}")

    atomate2_file = out_dir / "atomate2.yaml"
    atomate2_file.write_text(render_atomate2(config))
    print(f"wrote {atomate2_file}")

    for machine in config["machines"]:
        env_file = out_dir / f"env.{machine['name']}.sh"
        env_file.write_text(machine_env_sh(machine))
        print(f"wrote {env_file}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
